import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header_1 from "./header_1";
import Header0 from "./header0";
import Header1 from "./header1";
import Footerhk2 from "./Footer2hk";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <Header_1/>
	<Header0/>
	<Header1/>
 
 
        {children}
        
        <Footerhk2/>
 
        </body>
    </html>
  );
}
